site_name: Quiz CLI projekt blog

docs_dir: docs_src
site_dir: docs

theme:
  theme:
  logo: assets/pyladies.png
  language: cs
  name: material
  palette:
    primary: white
    accent: pink

nav:
  - Úvod: index.md
  - První sraz: 2026-02-05-prvni-sraz.md
  - Druhý sraz: 2026-02-12-druhy-sraz.md
  - Třetí sraz: 2026-02-19-treti-sraz.md
# - Čtvrtý sraz: # tady vlož odkaz na čtvrtý sraz
